//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZeroHunger.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Restaurant
    {
        public Restaurant()
        {
            this.Collect_Request = new HashSet<Collect_Request>();
        }
    
        public int Restaurant_Id { get; set; }
        public string Restaurant_Name { get; set; }
        public string Restaurant_Pass { get; set; }
    
        public virtual ICollection<Collect_Request> Collect_Request { get; set; }
    }
}
